ALTER TABLE "User"
ADD COLUMN "sessionVersion" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "adminVersion" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "RoleMapping"
ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
